In [12]:
import numpy as np

In [13]:
#ID array
arr1 = np.array([1, 2, 3, 4, 5])

print("1D Array:")
print(arr1)

1D Array:
[1 2 3 4 5]


In [14]:
#2D Array
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("2D Array:")
print(arr2)

2D Array:
[[1 2 3]
 [4 5 6]]


In [15]:
#3D Array
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("2D Array:")
print(arr2)

2D Array:
[[1 2 3]
 [4 5 6]]


In [16]:
print("Shape of arr1:", arr1.shape)
print("Shape of arr2:", arr2.shape)

Shape of arr1: (5,)
Shape of arr2: (2, 3)


In [17]:
arr3 = np.array([1, 2, 3, 4, 5, 6])

reshaped_arr = arr3.reshape(2, 3)

print("Reshaped Array:")
print(reshaped_arr)

Reshaped Array:
[[1 2 3]
 [4 5 6]]


In [18]:
print("First Element:", arr1[0])
print("Elements from index 1 to 3:", arr1[1:4])


First Element: 1
Elements from index 1 to 3: [2 3 4]


In [19]:
print("Sum:", np.sum(arr1))

Sum: 15


In [20]:
print("Mean:", np.mean(arr1))


Mean: 3.0


In [21]:
print("Maximum Value:", np.max(arr1))

Maximum Value: 5


In [22]:
print("Adding 10 to every element:")
print(arr1 + 10)

Adding 10 to every element:
[11 12 13 14 15]
